### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by mayburgos** [anitab-org/powerup-android#1113]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [ ] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [ ] Link all GSoC/Outreachy student's pages if applicable.
- [ ] Link Final Reports page if applicable.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by LSariel** [comment]
Is this issue still available? :)

**Comment by isabelcosta** [comment]
i just updated the wiki sidebar here https://github.com/systers/powerup-android/wiki
 
![image](https://user-images.githubusercontent.com/11148726/70749506-62182880-1d24-11ea-87d7-6839b8ff197c.png)

@systers/maintainers-powerup-android

**Comment by devanshi7799** [comment]
@isabelcosta @mayburgos @m-murad  i would like to work on this one. But i did not quite understand what is to be done. Can you help me?

**Comment by isabelcosta** [comment]
@devanshi7799 i will close this issue as there is nothing to be done. I did this is shown in this comment https://github.com/anitab-org/powerup-android/issues/1113#issuecomment-565189803

Can you find other issues to work on? We can help you if you need.
